### ISSUE TITLE
using useCallback hook

### ISSUE THREAD

**Issue by javadmsd** [sadafamininia99/React_basics#4]
You can use useCallback react hook to prevent re-generate when your component will be re-render

https://github.com/sadafamininia99/React_basics/blob/56c11c24d1c15bda1796631f97876a86eab2e505/src/components/NewExpense/ExpenseForm.js#L7

```js
const titleChangeHandler = useCallback((event) => {
   ...
}, [])

```

**Comment by sadafamininia99** [comment]
i got it ...

**Comment by javadmsd** [comment]
Great, so you can close this issue :)
